doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: -

        url: '%env(resolve:DATABASE_URL)%'


        types:
            user_user_id: 'App\Model\User\Entity\User\IdType'
            user_user_email: 'App\Model\User\Entity\User\EmailType'
            user_user_role: 'App\Model\User\Entity\User\RoleType'
            user_user_uchkak: 'App\Model\User\Entity\User\UchKakType'

            paseka_matkas_plemmatka_id: 'App\Model\Paseka\Entity\Matkas\PlemMatka\IdType'
            paseka_matkas_sparing_id: 'App\Model\Paseka\Entity\Matkas\Sparings\IdType'
            paseka_matkas_plemmatka_status: 'App\Model\Paseka\Entity\Matkas\PlemMatka\StatusType'
            paseka_matkas_plemmatka_department_id: 'App\Model\Paseka\Entity\Matkas\PlemMatka\Department\IdType'

            paseka_matkas_role_id: 'App\Model\Paseka\Entity\Matkas\Role\IdType'
            paseka_matkas_role_permissions: 'App\Model\Paseka\Entity\Matkas\Role\PermissionsType'
            paseka_matkas_kategoria_id: 'App\Model\Paseka\Entity\Matkas\Kategoria\IdType'
            paseka_matkas_kategoria_permissions: 'App\Model\Paseka\Entity\Matkas\Kategoria\PermissionsType'

            paseka_matkas_childmatka_status: 'App\Model\Paseka\Entity\Matkas\ChildMatka\StatusType'
            paseka_matkas_childmatka_id: 'App\Model\Paseka\Entity\Matkas\ChildMatka\IdType'
            paseka_matkas_childmatka_type: 'App\Model\Paseka\Entity\Matkas\ChildMatka\TypeType'

            mesto_okrug_id: 'App\Model\Mesto\Entity\Okrugs\IdType'
            mesto_okrug_oblast_id: 'App\Model\Mesto\Entity\Okrugs\Oblasts\IdType'
            mesto_okrug_oblast_raion_id: 'App\Model\Mesto\Entity\Okrugs\Oblasts\Raions\IdType'
            mesto_mestonomer_id: 'App\Model\Mesto\Entity\InfaMesto\IdType'

            paseka_rasa_id: 'App\Model\Paseka\Entity\Rasas\IdType'
            paseka_rasa_linia_id: 'App\Model\Paseka\Entity\Rasas\Linias\IdType'
            paseka_rasa_linia_nomer_id: 'App\Model\Paseka\Entity\Rasas\Linias\Nomers\IdType'


            paseka_uchasties_group_id: 'App\Model\Paseka\Entity\Uchasties\Group\IdType'
            paseka_uchasties_uchastie_id: 'App\Model\Paseka\Entity\Uchasties\Uchastie\IdType'
            paseka_uchasties_uchastie_status: 'App\Model\Paseka\Entity\Uchasties\Uchastie\StatusType'
            paseka_uchasties_uchastie_email: 'App\Model\Paseka\Entity\Uchasties\Uchastie\EmailType'
            paseka_uchasties_uchastie_uchkak: 'App\Model\Paseka\Entity\Uchasties\Uchastie\UchKakType'

            paseka_uchasties_persona_id: 'App\Model\Paseka\Entity\Uchasties\Personas\IdType'

            sezons_goda_id: 'App\Model\Sezons\Entity\Godas\IdType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Mesto:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Mesto/Entity'
                prefix: 'App\Model\Mesto\Entity'
                alias: Mesto
            Paseka:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Paseka/Entity'
                prefix: 'App\Model\Paseka\Entity'
                alias: Paseka
            Sezons:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Sezons/Entity'
                prefix: 'App\Model\Sezons\Entity'
                alias: Sezons
            Sait:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Sait/Entity'
                prefix: 'App\Model\Sait\Entity'
                alias: Sait
            Proekt:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Proekt/Entity'
                prefix: 'App\Model\Proekt\Entity'
                alias: Proekt